spring.application.name=edgarfeed
spring.datasource.url=jdbc:postgresql://localhost:5332/edgarfeed
spring.datasource.username=${DATABASE_USER:edgarfeed-user}
spring.datasource.password=${DATABASE_PASSWORD:edgarfeed}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
