spring.config.import=aws-secretsmanager:rds!db-1e95db06-9fef-4395-8bfa-74ada89d6168

spring.datasource.url=jdbc:postgresql://edgarfeed-db.cnqog0ggiubb.us-east-2.rds.amazonaws.com:5432/postgres
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.cloud.aws.region.static=us-east-2
